# Generated by Django 4.2.4 on 2024-08-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Produtos',
        ),
    ]
