# Generated by Django 4.2.4 on 2024-08-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_rename_produto_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco_promocional',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
