# Generated by Django 4.2.4 on 2024-08-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produtos_preco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='tipo',
        ),
    ]
