# Generated by Django 4.2.4 on 2024-08-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_remove_produtos_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='slug',
        ),
    ]
