# Generated by Django 4.2.4 on 2024-08-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_remove_produtos_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
