# Generated by Django 4.2.4 on 2024-04-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_pedido_contato_alter_pedido_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-id']},
        ),
    ]
