# Generated by Django 4.2.4 on 2024-05-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_pedido_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='contato',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cpf_cnpj',
            field=models.CharField(max_length=14),
        ),
    ]
